#:schema node_modules/wrangler/config-schema.json
name = "board-room"
compatibility_date = "2024-10-22"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "board-room"
database_id = "64baad39-5e5f-4055-8442-7b656c693be4"
migrations_dir = "migrations"

